resilience4j.retry:
  instances:
    trajano:
      maxAttempts: 3
      waitDuration: 1s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - org.aag.resilencetest.exceptions.RetryableException
      #ignoreExceptions:
      #  - io.github.robwin.exception.BusinessException